# Generated by Django 4.0.4 on 2022-09-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('ticker', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=2000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sector', models.CharField(max_length=30)),
                ('industry', models.CharField(max_length=30)),
                ('employee_count', models.IntegerField()),
                ('sic_no', models.IntegerField()),
                ('location', models.CharField(max_length=40)),
                ('exchange_id', models.IntegerField()),
                ('cik_no', models.IntegerField()),
                ('cuisp', models.CharField(max_length=20)),
                ('currency_id', models.IntegerField()),
                ('data_source_id', models.IntegerField()),
                ('ckr_log', models.BooleanField()),
                ('similar_fund_log', models.BooleanField()),
                ('address', models.CharField(max_length=70)),
                ('company_name', models.CharField(max_length=40)),
                ('phone_no', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=60)),
                ('is_active', models.BooleanField()),
                ('url_slug', models.CharField(max_length=40)),
                ('delisted_date', models.DateField()),
                ('delisted_reason', models.CharField(max_length=500)),
                ('image_name', models.CharField(max_length=50)),
                ('image_aspect_ratio', models.FloatField()),
                ('cumulative_return_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('returns', models.FloatField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('equity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.equities')),
            ],
        ),
    ]
