# Generated by Django 4.0.4 on 2022-09-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equities',
            old_name='cuisp',
            new_name='cusip',
        ),
        migrations.RenameField(
            model_name='equities',
            old_name='employee_count',
            new_name='employees_count',
        ),
    ]
